# Change these first
owner: dschense # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
#  - name: Google
#    url: https://www.google.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Broken Site
#    url: https://thissitedoesnotexist.com
#  - name: Test for HEAD
#    method: HEAD
#    url: https://www.google.com
#  - name: Secret Site
#    url: $SECRET_SITE
   - name: Mail
     url: https://mail.tr4sh.net
   - name: Mastodon
     url: https://social.tr4sh.net
   - name: Bitwarden
     url: https://vault.tr4sh.net
   - name: Jitsi
     url: https://videocall.tr4sh.net
   - name: TinyRSS
     url: https://tiny.tr4sh.net
   - name: Wallabag
     url: https://wallabag.tr4sh.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tr4sh.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Tr4sh.net
  introTitle: "**Tr4sh.net** Statusmonitor für öffentliche Dienste"
  introMessage: Hierbei handelt es sich um eine einfache Status Seite die Echtzeitdaten des [GitHub repository](https://github.com/dschense/status) nutzt.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
